import type { Product } from '../types/products';

export const mockProducts: Product[] = [
  {
    id: 1, name: 'Wireless Headphones', sku: 'EL-WH-001', category: 'Electronics',
    location: 'Warehouse A', quantity_on_hand: 500, quantity_available: 450,
    unit_price: 89.99, total_value: 44995, reorder_point: 100, max_stock: 600,
    days_since_movement: 12, turnover_rate: 7.2,
    health_score: 87.6, health_status: 'HEALTHY',
    availability_score: 85, turnover_score: 78, freshness_score: 92,
    balance_score: 88, value_score: 95,
    last_received: '2024-04-10', last_sold: '2024-04-18',
    supplier: 'SoundTech Co.', tags: ['electronics', 'audio', 'wireless'],
  },
  {
    id: 2, name: 'Gaming Mouse', sku: 'EL-GM-002', category: 'Electronics',
    location: 'Warehouse A', quantity_on_hand: 8, quantity_available: 5,
    unit_price: 59.99, total_value: 479.92, reorder_point: 50, max_stock: 300,
    days_since_movement: 45, turnover_rate: 1.1,
    health_score: 38.0, health_status: 'CRITICAL',
    availability_score: 25, turnover_score: 45, freshness_score: 30,
    balance_score: 40, value_score: 50,
    last_received: '2024-03-01', last_sold: '2024-03-05',
    supplier: 'PeripheralsPro', tags: ['electronics', 'gaming', 'peripherals'],
  },
  {
    id: 3, name: 'USB-C Hub', sku: 'EL-UC-003', category: 'Accessories',
    location: 'Warehouse B', quantity_on_hand: 180, quantity_available: 120,
    unit_price: 34.99, total_value: 6298.2, reorder_point: 60, max_stock: 250,
    days_since_movement: 22, turnover_rate: 4.5,
    health_score: 66.6, health_status: 'WARNING',
    availability_score: 72, turnover_score: 65, freshness_score: 58,
    balance_score: 70, value_score: 68,
    last_received: '2024-03-20', last_sold: '2024-03-28',
    supplier: 'ConnectAll Ltd.', tags: ['accessories', 'connectivity'],
  },
  {
    id: 4, name: 'Mechanical Keyboard', sku: 'EL-MK-004', category: 'Electronics',
    location: 'Warehouse A', quantity_on_hand: 350, quantity_available: 320,
    unit_price: 129.99, total_value: 45496.5, reorder_point: 80, max_stock: 400,
    days_since_movement: 5, turnover_rate: 8.9,
    health_score: 87.2, health_status: 'HEALTHY',
    availability_score: 90, turnover_score: 82, freshness_score: 88,
    balance_score: 85, value_score: 91,
    last_received: '2024-04-15', last_sold: '2024-04-19',
    supplier: 'KeyMaster Inc.', tags: ['electronics', 'peripherals', 'gaming'],
  },
  {
    id: 5, name: '4K Monitor', sku: 'EL-4M-005', category: 'Electronics',
    location: 'Warehouse B', quantity_on_hand: 90, quantity_available: 45,
    unit_price: 449.99, total_value: 40499.1, reorder_point: 20, max_stock: 100,
    days_since_movement: 30, turnover_rate: 2.8,
    health_score: 55.0, health_status: 'WARNING',
    availability_score: 55, turnover_score: 48, freshness_score: 62,
    balance_score: 52, value_score: 58,
    last_received: '2024-03-10', last_sold: '2024-03-20',
    supplier: 'VisionTech', tags: ['electronics', 'display', 'premium'],
  },
  {
    id: 6, name: 'Webcam Pro', sku: 'EL-WC-006', category: 'Electronics',
    location: 'Warehouse A', quantity_on_hand: 300, quantity_available: 280,
    unit_price: 79.99, total_value: 23997, reorder_point: 60, max_stock: 350,
    days_since_movement: 3, turnover_rate: 9.4,
    health_score: 90.4, health_status: 'HEALTHY',
    availability_score: 95, turnover_score: 88, freshness_score: 90,
    balance_score: 92, value_score: 87,
    last_received: '2024-04-17', last_sold: '2024-04-19',
    supplier: 'ClearVision Ltd.', tags: ['electronics', 'video', 'remote-work'],
  },
  {
    id: 7, name: 'Laptop Stand', sku: 'AC-LS-007', category: 'Accessories',
    location: 'Warehouse C', quantity_on_hand: 600, quantity_available: 580,
    unit_price: 24.99, total_value: 14994, reorder_point: 100, max_stock: 700,
    days_since_movement: 8, turnover_rate: 6.1,
    health_score: 82.0, health_status: 'HEALTHY',
    availability_score: 88, turnover_score: 74, freshness_score: 85,
    balance_score: 80, value_score: 83,
    last_received: '2024-04-12', last_sold: '2024-04-18',
    supplier: 'ErgoDesk Co.', tags: ['accessories', 'ergonomics', 'remote-work'],
  },
  {
    id: 8, name: 'Portable SSD 1TB', sku: 'ST-PS-008', category: 'Storage',
    location: 'Warehouse B', quantity_on_hand: 12, quantity_available: 10,
    unit_price: 109.99, total_value: 1319.88, reorder_point: 30, max_stock: 200,
    days_since_movement: 60, turnover_rate: 0.8,
    health_score: 28.5, health_status: 'CRITICAL',
    availability_score: 20, turnover_score: 30, freshness_score: 22,
    balance_score: 35, value_score: 35,
    last_received: '2024-02-15', last_sold: '2024-02-20',
    supplier: 'FlashStore Inc.', tags: ['storage', 'portable', 'premium'],
  },
  {
    id: 9, name: 'Wireless Charger Pad', sku: 'AC-WCP-009', category: 'Accessories',
    location: 'Warehouse A', quantity_on_hand: 420, quantity_available: 410,
    unit_price: 19.99, total_value: 8395.8, reorder_point: 80, max_stock: 500,
    days_since_movement: 6, turnover_rate: 8.2,
    health_score: 88.0, health_status: 'HEALTHY',
    availability_score: 92, turnover_score: 85, freshness_score: 89,
    balance_score: 86, value_score: 88,
    last_received: '2024-04-14', last_sold: '2024-04-19',
    supplier: 'ChargeFast Ltd.', tags: ['accessories', 'wireless', 'charging'],
  },
  {
    id: 10, name: 'Smart Speaker', sku: 'SM-SS-010', category: 'Smart Home',
    location: 'Warehouse C', quantity_on_hand: 75, quantity_available: 40,
    unit_price: 149.99, total_value: 11249.25, reorder_point: 25, max_stock: 150,
    days_since_movement: 35, turnover_rate: 3.1,
    health_score: 51.0, health_status: 'WARNING',
    availability_score: 48, turnover_score: 55, freshness_score: 50,
    balance_score: 50, value_score: 52,
    last_received: '2024-03-05', last_sold: '2024-03-15',
    supplier: 'VoiceWave Inc.', tags: ['smart-home', 'audio', 'wireless'],
  },
  {
    id: 11, name: 'HDMI Cable 2m', sku: 'CA-HC-011', category: 'Cables',
    location: 'Warehouse B', quantity_on_hand: 800, quantity_available: 790,
    unit_price: 9.99, total_value: 7992, reorder_point: 150, max_stock: 1000,
    days_since_movement: 2, turnover_rate: 11.5,
    health_score: 93.0, health_status: 'HEALTHY',
    availability_score: 98, turnover_score: 95, freshness_score: 93,
    balance_score: 90, value_score: 89,
    last_received: '2024-04-18', last_sold: '2024-04-19',
    supplier: 'CablePro Systems', tags: ['cables', 'connectivity', 'display'],
  },
  {
    id: 12, name: 'Noise-Cancelling Earbuds', sku: 'EL-NCE-012', category: 'Electronics',
    location: 'Warehouse A', quantity_on_hand: 55, quantity_available: 30,
    unit_price: 199.99, total_value: 10999.45, reorder_point: 40, max_stock: 200,
    days_since_movement: 18, turnover_rate: 4.0,
    health_score: 62.0, health_status: 'WARNING',
    availability_score: 60, turnover_score: 58, freshness_score: 65,
    balance_score: 62, value_score: 65,
    last_received: '2024-03-28', last_sold: '2024-04-07',
    supplier: 'SoundTech Co.', tags: ['electronics', 'audio', 'wireless', 'premium'],
  },
];

export const CATEGORIES = ['All', 'Electronics', 'Accessories', 'Storage', 'Smart Home', 'Cables'];
export const LOCATIONS = ['All', 'Warehouse A', 'Warehouse B', 'Warehouse C'];
